[cmake.cache]
FT_DISABLE_BZIP2 = false
FT_REQUIRE_BZIP2 = true
FT_DISABLE_HARFBUZZ = false
FT_REQUIRE_HARFBUZZ = true
FT_DYNAMIC_HARFBUZZ = false
FT_DISABLE_PNG = false
FT_DISABLE_ZLIB = false
FT_DISABLE_BROTLI = false

