[cmake.cache]
WEBP_BUILD_ANIM_UTILS = false
WEBP_BUILD_CWEBP = false
WEBP_BUILD_DWEBP = false
WEBP_BUILD_GIF2WEBP = false
WEBP_BUILD_IMG2WEBP = false
WEBP_BUILD_VWEBP = false
WEBP_BUILD_WEBPINFO = false
WEBP_BUILD_WEBPMUX = false
WEBP_BUILD_EXTRAS = false
WEBP_BUILD_FUZZTEST = false
WEBP_BUILD_LIBWEBPMUX = true

