repo_names = ["OpenMeta"]

[cmake.cache]
OPENMETA_BUILD_TOOLS = true
OPENMETA_BUILD_TESTS = false
OPENMETA_BUILD_FUZZERS = false
OPENMETA_BUILD_FUZZTEST = false
OPENMETA_FUZZTEST_FUZZING_MODE = false
OPENMETA_BUILD_DOCS = false
OPENMETA_BUILD_SPHINX_DOCS = false
OPENMETA_ENABLE_RAPIDFUZZ = true
OPENMETA_ENABLE_C2PA_VERIFY = false
