from __future__ import annotations

import shutil

from ..runner import banner
from ..license_policy import LGPL_DYNAMIC
from ..vcpkg_import import add_debug_postfix, copy_bin_payload, find_triplet, resolve_export_zip, stage_export


def enabled(builder, _repo) -> bool:
    return builder.platform.os == "windows"


def _zip_path(builder, env=None):
    return resolve_export_zip(
        builder,
        env,
        default_filename="vcpkg-export-libiconv.zip",
        env_names=("LIBICONV_VCPKG_EXPORT_ZIP", "VCPKG_LIBICONV_EXPORT_ZIP"),
        glob_pattern="vcpkg-export-libiconv*.zip",
    )


def missing_source_skip(builder, repo, _path) -> bool | None:
    if builder.platform.os != "windows":
        return None
    zip_path = _zip_path(builder)
    if zip_path.exists():
        return False
    if repo.optional:
        print(f"[skip] {repo.name}: missing vcpkg export zip at {zip_path}")
        return True
    return False


def skip_update(builder, _repo) -> bool:
    return builder.platform.os == "windows"


def stamp_payload(builder, _repo, _ctx, payload: dict) -> None:
    if builder.platform.os != "windows":
        return
    zip_path = _zip_path(builder)
    payload["vcpkg_export_zip"] = str(zip_path)
    if zip_path.exists():
        st = zip_path.stat()
        payload["vcpkg_export_zip_size"] = int(st.st_size)
        payload["vcpkg_export_zip_mtime"] = int(st.st_mtime)


def build(builder, ctx, env: dict[str, str]) -> None:
    if builder.platform.os != "windows":
        raise RuntimeError("libiconv build system is only supported on Windows")

    zip_path = _zip_path(builder, env)
    installed_dir = stage_export(builder, ctx, env, zip_path, "_libiconv_vcpkg_export")
    if installed_dir is None:
        return

    static_linkage = bool(builder.config.global_cfg.static_default)
    triplet_dir = find_triplet(installed_dir, "include/iconv.h", zip_path, prefer_static=static_linkage)
    include_src = triplet_dir / "include"
    lib_src = triplet_dir / "lib"
    debug_lib_src = triplet_dir / "debug" / "lib"
    bin_src = triplet_dir / "bin"

    lgpl_dynamic = builder.license_profile is not None and builder.license_profile.name == LGPL_DYNAMIC
    if lgpl_dynamic:
        dll_names = [path.name.lower() for path in bin_src.glob("*.dll")]
        missing_dlls = [stem for stem in ("iconv", "charset") if not any(stem in name for name in dll_names)]
        if missing_dlls:
            raise RuntimeError(
                "lgpl-dynamic requires a shared libiconv vcpkg export; missing DLLs for: "
                f"{', '.join(missing_dlls)} in {bin_src}"
            )

    required = [
        include_src / "iconv.h",
        lib_src / "iconv.lib",
        lib_src / "charset.lib",
        debug_lib_src / "iconv.lib",
        debug_lib_src / "charset.lib",
    ]
    missing = [p for p in required if not p.exists()]
    if missing:
        wanted = "\n".join(f"  - {p}" for p in missing)
        raise RuntimeError(f"libiconv vcpkg export is missing expected files:\n{wanted}")

    debug_postfix = str(builder.config.global_cfg.windows.get("debug_postfix", "d"))
    banner(f"{ctx.repo.name} ({ctx.build_type}) - install")

    inc_dst = ctx.install_prefix / "include"
    lib_dst = ctx.install_prefix / "lib"
    bin_dst = ctx.install_prefix / "bin"
    inc_dst.mkdir(parents=True, exist_ok=True)
    lib_dst.mkdir(parents=True, exist_ok=True)

    for item in include_src.iterdir():
        if item.is_file():
            shutil.copy2(item, inc_dst / item.name)
    for item in lib_src.iterdir():
        if item.is_file():
            shutil.copy2(item, lib_dst / item.name)
    for item in debug_lib_src.iterdir():
        if item.is_file():
            shutil.copy2(item, lib_dst / add_debug_postfix(item.name, debug_postfix))

    copy_bin_payload(bin_src, bin_dst, "libiconv", prefer_static=static_linkage)

    cmake_dir = ctx.install_prefix / "lib" / "cmake" / "Iconv"
    cmake_dir.mkdir(parents=True, exist_ok=True)
    (cmake_dir / "IconvConfig.cmake").write_text(
        "\n".join(
            [
                "# Generated by oiio-builder (imported from vcpkg export)",
                "set(Iconv_FOUND TRUE)",
                "set(Iconv_IS_BUILT_IN FALSE)",
                "",
                "get_filename_component(_iconv_prefix \"${CMAKE_CURRENT_LIST_DIR}/../../..\" ABSOLUTE)",
                "set(_iconv_incdir \"${_iconv_prefix}/include\")",
                "set(_iconv_libdir \"${_iconv_prefix}/lib\")",
                f"set(_iconv_debug_postfix \"{debug_postfix}\")",
                "",
                "set(_iconv_lib_release \"${_iconv_libdir}/iconv.lib\")",
                "set(_iconv_lib_debug \"${_iconv_libdir}/iconv${_iconv_debug_postfix}.lib\")",
                "set(_charset_lib_release \"${_iconv_libdir}/charset.lib\")",
                "set(_charset_lib_debug \"${_iconv_libdir}/charset${_iconv_debug_postfix}.lib\")",
                "",
                "if(NOT TARGET Iconv::Charset)",
                "  add_library(Iconv::Charset UNKNOWN IMPORTED)",
                "  set_property(TARGET Iconv::Charset PROPERTY IMPORTED_CONFIGURATIONS \"RELEASE;DEBUG\")",
                "  set_target_properties(Iconv::Charset PROPERTIES",
                "    INTERFACE_INCLUDE_DIRECTORIES \"${_iconv_incdir}\"",
                "    IMPORTED_LOCATION \"${_charset_lib_release}\"",
                "    IMPORTED_LOCATION_RELEASE \"${_charset_lib_release}\"",
                "    IMPORTED_LOCATION_DEBUG \"${_charset_lib_debug}\"",
                "    MAP_IMPORTED_CONFIG_MINSIZEREL Release",
                "    MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release",
                "    MAP_IMPORTED_CONFIG_ASAN Release",
                "  )",
                "endif()",
                "",
                "if(NOT TARGET Iconv::Iconv)",
                "  add_library(Iconv::Iconv UNKNOWN IMPORTED)",
                "  set_property(TARGET Iconv::Iconv PROPERTY IMPORTED_CONFIGURATIONS \"RELEASE;DEBUG\")",
                "  set_target_properties(Iconv::Iconv PROPERTIES",
                "    INTERFACE_INCLUDE_DIRECTORIES \"${_iconv_incdir}\"",
                "    IMPORTED_LOCATION \"${_iconv_lib_release}\"",
                "    IMPORTED_LOCATION_RELEASE \"${_iconv_lib_release}\"",
                "    IMPORTED_LOCATION_DEBUG \"${_iconv_lib_debug}\"",
                "    INTERFACE_LINK_LIBRARIES \"Iconv::Charset\"",
                "    MAP_IMPORTED_CONFIG_MINSIZEREL Release",
                "    MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release",
                "    MAP_IMPORTED_CONFIG_ASAN Release",
                "  )",
                "endif()",
                "",
                "set(Iconv_INCLUDE_DIR \"${_iconv_incdir}\")",
                "set(Iconv_INCLUDE_DIRS \"${_iconv_incdir}\")",
                "set(Iconv_LIBRARY \"${_iconv_lib_release}\")",
                "set(Iconv_LIBRARIES \"${_iconv_lib_release};${_charset_lib_release}\")",
                "",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
