from __future__ import annotations

import shutil

from ..runner import banner
from ..vcpkg_import import add_debug_postfix, copy_bin_payload, copy_include_tree, find_triplet, resolve_export_zip, stage_export


def enabled(builder, _repo) -> bool:
    return bool(builder.config.global_cfg.build_libvpx)


def resolve_build_system(builder, _repo, _src_dir) -> str | None:
    if builder.platform.os == "windows":
        return "libvpx"
    return None


def _zip_path(builder, env=None):
    return resolve_export_zip(
        builder,
        env,
        default_filename="vcpkg-export-libvpx.zip",
        env_names=("LIBVPX_VCPKG_EXPORT_ZIP", "VCPKG_LIBVPX_EXPORT_ZIP", "VPX_VCPKG_EXPORT_ZIP", "VCPKG_VPX_EXPORT_ZIP"),
        glob_pattern="vcpkg-export-libvpx*.zip",
    )


def missing_source_skip(builder, repo, _path) -> bool | None:
    if builder.platform.os != "windows":
        return None
    zip_path = _zip_path(builder)
    if zip_path.exists():
        return False
    if repo.optional:
        print(f"[skip] {repo.name}: missing vcpkg export zip at {zip_path}")
        return True
    return False


def skip_update(builder, _repo) -> bool:
    return builder.platform.os == "windows"


def stamp_payload(builder, _repo, _ctx, payload: dict) -> None:
    if builder.platform.os != "windows":
        return
    zip_path = _zip_path(builder)
    payload["vcpkg_export_zip"] = str(zip_path)
    if zip_path.exists():
        st = zip_path.stat()
        payload["vcpkg_export_zip_size"] = int(st.st_size)
        payload["vcpkg_export_zip_mtime"] = int(st.st_mtime)


def build(builder, ctx, env: dict[str, str]) -> None:
    if builder.platform.os != "windows":
        raise RuntimeError("libvpx vcpkg import build system is only supported on Windows")

    zip_path = _zip_path(builder, env)
    installed_dir = stage_export(builder, ctx, env, zip_path, "_libvpx_vcpkg_export")
    if installed_dir is None:
        return

    triplet_dir = find_triplet(installed_dir, "include/vpx/vpx_codec.h", zip_path)
    include_src = triplet_dir / "include"
    lib_src = triplet_dir / "lib"
    debug_lib_src = triplet_dir / "debug" / "lib"
    bin_src = triplet_dir / "bin"

    def _pick_lib(dir_path):
        for name in ("vpx.lib", "libvpx.lib"):
            candidate = dir_path / name
            if candidate.exists():
                return candidate
        matches = sorted(dir_path.glob("*vpx*.lib"))
        return matches[0] if matches else None

    vpx_release = _pick_lib(lib_src)
    vpx_debug = _pick_lib(debug_lib_src)
    required = [include_src / "vpx" / "vpx_codec.h", vpx_release, vpx_debug]
    missing = [p for p in required if not p or not p.exists()]
    if missing:
        wanted = "\n".join(f"  - {p}" for p in missing)
        raise RuntimeError(f"libvpx vcpkg export is missing expected files:\n{wanted}")

    debug_postfix = str(builder.config.global_cfg.windows.get("debug_postfix", "d"))

    banner(f"{ctx.repo.name} ({ctx.build_type}) - install")
    include_dst = ctx.install_prefix / "include"
    lib_dst = ctx.install_prefix / "lib"
    bin_dst = ctx.install_prefix / "bin"
    copy_include_tree(include_src, include_dst)
    lib_dst.mkdir(parents=True, exist_ok=True)
    if vpx_release is not None:
        shutil.copy2(vpx_release, lib_dst / vpx_release.name)
    if vpx_debug is not None:
        shutil.copy2(vpx_debug, lib_dst / add_debug_postfix(vpx_release.name if vpx_release is not None else vpx_debug.name, debug_postfix))

    pkgconfig_src = lib_src / "pkgconfig"
    if pkgconfig_src.is_dir():
        pkgconfig_dst = lib_dst / "pkgconfig"
        pkgconfig_dst.mkdir(parents=True, exist_ok=True)
        for item in pkgconfig_src.iterdir():
            if item.is_file() and item.suffix.lower() == ".pc":
                shutil.copy2(item, pkgconfig_dst / item.name)

    copy_bin_payload(bin_src, bin_dst, "libvpx")

    release_name = vpx_release.name if vpx_release is not None else "vpx.lib"
    debug_name = add_debug_postfix(release_name, debug_postfix)
    libvpx_config = "\n".join(
        [
            "# Generated by oiio-builder (imported from vcpkg export)",
            "set(libvpx_FOUND TRUE)",
            "set(VPX_FOUND TRUE)",
            "",
            "get_filename_component(_libvpx_prefix \"${CMAKE_CURRENT_LIST_DIR}/../../..\" ABSOLUTE)",
            "set(_libvpx_incdir \"${_libvpx_prefix}/include\")",
            "set(_libvpx_libdir \"${_libvpx_prefix}/lib\")",
            "",
            "if(NOT TARGET libvpx::vpx)",
            "  add_library(libvpx::vpx UNKNOWN IMPORTED)",
            "  set_property(TARGET libvpx::vpx PROPERTY IMPORTED_CONFIGURATIONS \"RELEASE;DEBUG\")",
            "  set_target_properties(libvpx::vpx PROPERTIES",
            "    INTERFACE_INCLUDE_DIRECTORIES \"${_libvpx_incdir}\"",
            f"    IMPORTED_LOCATION_RELEASE \"${{_libvpx_libdir}}/{release_name}\"",
            f"    IMPORTED_LOCATION_DEBUG \"${{_libvpx_libdir}}/{debug_name}\"",
            "    MAP_IMPORTED_CONFIG_MINSIZEREL Release",
            "    MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release",
            "    MAP_IMPORTED_CONFIG_ASAN Release",
            "  )",
            "endif()",
            "",
            "if(TARGET libvpx::vpx AND NOT TARGET VPX::vpx)",
            "  add_library(VPX::vpx INTERFACE IMPORTED)",
            "  target_link_libraries(VPX::vpx INTERFACE libvpx::vpx)",
            "endif()",
            "",
            "if(TARGET libvpx::vpx AND NOT TARGET VPX::VPX)",
            "  add_library(VPX::VPX INTERFACE IMPORTED)",
            "  target_link_libraries(VPX::VPX INTERFACE libvpx::vpx)",
            "endif()",
            "",
            "set(VPX_INCLUDE_DIR \"${_libvpx_incdir}\")",
            "set(VPX_INCLUDE_DIRS \"${_libvpx_incdir}\")",
            f"set(VPX_LIBRARY \"${{_libvpx_libdir}}/{release_name}\")",
            f"set(VPX_LIBRARIES \"${{_libvpx_libdir}}/{release_name}\")",
            "",
        ]
    ) + "\n"

    for package_dir, config_name in (
        (lib_dst / "cmake" / "libvpx", "libvpxConfig.cmake"),
        (lib_dst / "cmake" / "VPX", "VPXConfig.cmake"),
    ):
        package_dir.mkdir(parents=True, exist_ok=True)
        (package_dir / config_name).write_text(libvpx_config, encoding="utf-8")


def autotools_args(builder, _repo) -> list[str]:
    args = [
        "--disable-examples",
        "--disable-tools",
        "--disable-docs",
        "--disable-unit-tests",
    ]
    if builder.config.global_cfg.pic:
        args.append("--enable-pic")
    return args
