from __future__ import annotations

import shutil

from .policy import qt6_enabled
from ..runner import banner
from ..vcpkg_import import add_debug_postfix, copy_bin_payload, copy_include_tree, find_triplet, resolve_export_zip, stage_export


def enabled(builder, _repo) -> bool:
    return builder.platform.os == "windows" and qt6_enabled(builder)


def _zip_path(builder, env=None):
    return resolve_export_zip(
        builder,
        env,
        default_filename="vcpkg-export-openssl.zip",
        env_names=("OPENSSL_VCPKG_EXPORT_ZIP", "VCPKG_OPENSSL_EXPORT_ZIP"),
        glob_pattern="vcpkg-export-openssl*.zip",
    )


def missing_source_skip(builder, repo, _path) -> bool | None:
    if builder.platform.os != "windows":
        return None
    zip_path = _zip_path(builder)
    if zip_path.exists():
        return False
    if repo.optional:
        print(f"[skip] {repo.name}: missing vcpkg export zip at {zip_path}")
        return True
    return False


def skip_update(builder, _repo) -> bool:
    return builder.platform.os == "windows"


def stamp_payload(builder, _repo, _ctx, payload: dict) -> None:
    if builder.platform.os != "windows":
        return
    zip_path = _zip_path(builder)
    payload["vcpkg_export_zip"] = str(zip_path)
    if zip_path.exists():
        st = zip_path.stat()
        payload["vcpkg_export_zip_size"] = int(st.st_size)
        payload["vcpkg_export_zip_mtime"] = int(st.st_mtime)


def build(builder, ctx, env: dict[str, str]) -> None:
    if builder.platform.os != "windows":
        raise RuntimeError("openssl build system is only supported on Windows")

    zip_path = _zip_path(builder, env)
    installed_dir = stage_export(builder, ctx, env, zip_path, "_openssl_vcpkg_export")
    if installed_dir is None:
        return

    triplet_dir = find_triplet(installed_dir, "include/openssl/ssl.h", zip_path)
    include_src = triplet_dir / "include"
    lib_src = triplet_dir / "lib"
    debug_lib_src = triplet_dir / "debug" / "lib"
    bin_src = triplet_dir / "bin"

    def _pick_lib(dir_path, stems):
        for stem in stems:
            p = dir_path / stem
            if p.exists():
                return p
        return None

    ssl_release = _pick_lib(lib_src, ["libssl.lib", "ssl.lib"])
    crypto_release = _pick_lib(lib_src, ["libcrypto.lib", "crypto.lib"])
    ssl_debug = _pick_lib(debug_lib_src, ["libssl.lib", "ssl.lib"])
    crypto_debug = _pick_lib(debug_lib_src, ["libcrypto.lib", "crypto.lib"])

    required = [
        include_src / "openssl" / "ssl.h",
        ssl_release,
        crypto_release,
        ssl_debug,
        crypto_debug,
    ]
    missing = [p for p in required if not p or not p.exists()]
    if missing:
        wanted = "\n".join(f"  - {p}" for p in missing)
        raise RuntimeError(f"openssl vcpkg export is missing expected files:\n{wanted}")

    debug_postfix = str(builder.config.global_cfg.windows.get("debug_postfix", "d"))
    banner(f"{ctx.repo.name} ({ctx.build_type}) - install")

    inc_dst = ctx.install_prefix / "include"
    lib_dst = ctx.install_prefix / "lib"
    bin_dst = ctx.install_prefix / "bin"
    copy_include_tree(include_src, inc_dst)
    lib_dst.mkdir(parents=True, exist_ok=True)

    for item in lib_src.iterdir():
        if item.is_file() and item.suffix.lower() == ".lib":
            shutil.copy2(item, lib_dst / item.name)
    for item in debug_lib_src.iterdir():
        if item.is_file() and item.suffix.lower() == ".lib":
            shutil.copy2(item, lib_dst / add_debug_postfix(item.name, debug_postfix))

    copy_bin_payload(bin_src, bin_dst, "openssl")

    cmake_dir = ctx.install_prefix / "lib" / "cmake" / "OpenSSL"
    cmake_dir.mkdir(parents=True, exist_ok=True)

    ssl_name = ssl_release.name if ssl_release else "libssl.lib"
    crypto_name = crypto_release.name if crypto_release else "libcrypto.lib"
    ssl_dbg_name = add_debug_postfix(ssl_name, debug_postfix)
    crypto_dbg_name = add_debug_postfix(crypto_name, debug_postfix)

    (cmake_dir / "OpenSSLConfig.cmake").write_text(
        "\n".join(
            [
                "# Generated by oiio-builder (imported from vcpkg export)",
                "set(OpenSSL_FOUND TRUE)",
                "",
                "get_filename_component(_openssl_prefix \"${CMAKE_CURRENT_LIST_DIR}/../../..\" ABSOLUTE)",
                "set(OPENSSL_ROOT_DIR \"${_openssl_prefix}\")",
                "set(OPENSSL_INCLUDE_DIR \"${_openssl_prefix}/include\")",
                "set(OPENSSL_INCLUDE_DIRS \"${OPENSSL_INCLUDE_DIR}\")",
                "set(_openssl_libdir \"${_openssl_prefix}/lib\")",
                f"set(_openssl_debug_postfix \"{debug_postfix}\")",
                "",
                f"set(OPENSSL_SSL_LIBRARY \"${{_openssl_libdir}}/{ssl_name}\")",
                f"set(OPENSSL_CRYPTO_LIBRARY \"${{_openssl_libdir}}/{crypto_name}\")",
                "set(OPENSSL_LIBRARIES \"${OPENSSL_SSL_LIBRARY};${OPENSSL_CRYPTO_LIBRARY}\")",
                "",
                "if(NOT TARGET OpenSSL::Crypto)",
                "  add_library(OpenSSL::Crypto UNKNOWN IMPORTED)",
                "  set_property(TARGET OpenSSL::Crypto PROPERTY IMPORTED_CONFIGURATIONS \"RELEASE;DEBUG\")",
                "  set_target_properties(OpenSSL::Crypto PROPERTIES",
                "    INTERFACE_INCLUDE_DIRECTORIES \"${OPENSSL_INCLUDE_DIR}\"",
                f"    IMPORTED_LOCATION_RELEASE \"${{_openssl_libdir}}/{crypto_name}\"",
                f"    IMPORTED_LOCATION_DEBUG \"${{_openssl_libdir}}/{crypto_dbg_name}\"",
                "    MAP_IMPORTED_CONFIG_MINSIZEREL Release",
                "    MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release",
                "    MAP_IMPORTED_CONFIG_ASAN Release",
                "  )",
                "endif()",
                "",
                "if(NOT TARGET OpenSSL::SSL)",
                "  add_library(OpenSSL::SSL UNKNOWN IMPORTED)",
                "  set_property(TARGET OpenSSL::SSL PROPERTY IMPORTED_CONFIGURATIONS \"RELEASE;DEBUG\")",
                "  set_target_properties(OpenSSL::SSL PROPERTIES",
                "    INTERFACE_INCLUDE_DIRECTORIES \"${OPENSSL_INCLUDE_DIR}\"",
                f"    IMPORTED_LOCATION_RELEASE \"${{_openssl_libdir}}/{ssl_name}\"",
                f"    IMPORTED_LOCATION_DEBUG \"${{_openssl_libdir}}/{ssl_dbg_name}\"",
                "    INTERFACE_LINK_LIBRARIES OpenSSL::Crypto",
                "    MAP_IMPORTED_CONFIG_MINSIZEREL Release",
                "    MAP_IMPORTED_CONFIG_RELWITHDEBINFO Release",
                "    MAP_IMPORTED_CONFIG_ASAN Release",
                "  )",
                "endif()",
                "",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
